version: '3.4'

services:
  # client:
  #   image: nginx-client
  #   build:
  #     context: .
  #     target: nginx-client
  #   restart: always
  #   ports:
  #     - 3080:80
  #   volumes:
  #     - /share/Container/chatgptclone/application/client/node_modules:/app/node_modules
  #   depends_on:
  #     - api
  api:
    ports:
      - 9000:3080
    depends_on:
      - mongodb
      - meilisearch
    image: node-api
    build:
      context: .
      target: node-api
    restart: always
    env_file:
      - /share/Container/chatgptclone/application/api/.env
    environment:
      - HOST=0.0.0.0
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/chatgpt-clone
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_HTTP_ADDR=meilisearch:7700
    volumes:
      - /share/Container/chatgptclone/application/client/node_modules:/app/node_modules
      - /share/Container/chatgptclone/application/api:/api
      - /share/Container/chatgptclone/application/api/node_modules:/api/node_modules
  mongodb:
    ports:
      - 27017:27017
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - /share/Container/chatgptclone/application/data-node:/data/db
    command: mongod --noauth
  meilisearch:
    image: getmeili/meilisearch
    ports:
      - 7700:7700
    env_file:
      - /share/Container/chatgptclone/application/api/.env
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_HTTP_ADDR=meilisearch:7700
    volumes:
      - /share/Container/chatgptclone/application/meili_data:/data.ms
